name 'puppetlabs-auth_conf'
version '0.0.5'
source 'git://github.com/puppetlabs/puppetlabs-auth_conf'
author 'puppetlabs'
license 'Apache 2.0'
summary 'Puppet management for auth.conf'
description 'Puppet module to configure and manage Puppet\'s auth.conf file'

dependency 'puppetlabs/stdlib', '>= 2.5.1'
dependency 'ripienaar/concat', '>= 0.2.0'
